# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fsBooksApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='in_print',
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
    ]
