# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretsApp', '0002_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='like',
        ),
    ]
