# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsApp', '0003_remove_secret_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='secrets',
        ),
        migrations.AddField(
            model_name='secret',
            name='likes',
            field=models.ManyToManyField(related_name='secrets', to='secretsApp.Like'),
        ),
    ]
