# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretsApp', '0004_auto_20170720_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='users',
        ),
        migrations.RemoveField(
            model_name='secret',
            name='likes',
        ),
        migrations.AddField(
            model_name='like',
            name='secret',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='secretsApp.Secret'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='secretsApp.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(),
        ),
    ]
