# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretsApp', '0008_auto_20170720_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='secret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='secretsApp.Secret'),
        ),
    ]
