# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretsApp', '0009_auto_20170721_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='secret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='secretsApp.Secret'),
        ),
        migrations.AlterField(
            model_name='like',
            name='total_liked',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
