# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsApp', '0011_auto_20170721_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='total_liked',
            field=models.PositiveIntegerField(),
        ),
    ]
