# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretsApp', '0012_auto_20170721_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='users',
        ),
    ]
