# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviewApp.Book'),
        ),
    ]
